[[release_notes]]
file_name = "11904_Add_support_for_KHR_texture_transform.md"

[[release_notes]]
file_name = "12013_Upstreaming_bevy_color.md"

[[release_notes]]
file_name = "11823_Immediately_apply_deferred_system_params_in_Systemrun.md"

[[release_notes]]
file_name = "11906_Run_the_multithreaded_executor_at_the_end_of_each_system_t.md"

[[release_notes]]
file_name = "12147_bevy_color_Added_Color_Conversion_Mermaid_Diagram.md"

[[release_notes]]
file_name = "10701_Cubic_splines_overhaul.md"

[[release_notes]]
file_name = "12163_Migrate_from_LegacyColor_to_bevy_colorColor.md"

[[release_notes]]
file_name = "12211_Add_coordinate_axes_gizmo.md"

[[release_notes]]
file_name = "12228_Add_basic_light_gizmos.md"

[[release_notes]]
file_name = "11165_Decouple_BackgroundColor_from_UiImage.md"

[[release_notes]]
file_name = "12100_Add_WinitEvent_aggregate_event_for_synchronized_window_eve.md"

[[release_notes]]
file_name = "5781_bevy_reflect_Recursive_registration.md"

[[release_notes]]
file_name = "11341_Add_bevy_dev_tools_crate.md"

[[release_notes]]
file_name = "12331_We_must_have_googly_eyes_new_Game_example.md"

[[release_notes]]
file_name = "11989_Implement_the_AnimationGraph_allowing_for_multiple_animati.md"

[[release_notes]]
file_name = "11535_Query_Joins.md"

[[release_notes]]
file_name = "11658_Add_Rotation2d.md"

[[release_notes]]
file_name = "12252_Gizmo_line_joints.md"

[[release_notes]]
file_name = "12430_Gizmo_3d_grids.md"

[[release_notes]]
file_name = "12187_Alignment_API_for_Transforms.md"

[[release_notes]]
file_name = "12484_Uniform_point_sampling_methods_for_some_primitive_shapes.md"

[[release_notes]]
file_name = "9135_Add_pipeline_statistics.md"

[[release_notes]]
file_name = "12550_Use_asyncfn_in_traits_rather_than_BoxedFuture.md"

[[release_notes]]
file_name = "11237_Add_a_gizmobased_overlay_to_show_UI_node_outlines_Adopted.md"

[[release_notes]]
file_name = "12500_Add_border_radius_to_UI_nodes_adopted.md"

[[release_notes]]
file_name = "12508_Add_Triangle3d_primitive_to_bevy_mathprimitives.md"

[[release_notes]]
file_name = "10164_Meshlet_rendering_initial_feature.md"

[[release_notes]]
file_name = "12205_Get_Bevy_building_for_WebAssembly_with_multithreading.md"

[[release_notes]]
file_name = "12394_Gizmo_line_styles.md"

[[release_notes]]
file_name = "12747_Move_Point_out_of_cubic_splines_module_and_expand_it.md"

[[release_notes]]
file_name = "12135_Support_wireframes_for_2D_meshes.md"

[[release_notes]]
file_name = "12453_Improve_performance_by_binning_together_opaque_items_inste.md"

[[release_notes]]
file_name = "12547_Add_AsyncSeek_trait_to_Reader_to_be_able_to_seek_inside_as.md"

[[release_notes]]
file_name = "9202_Refactor_App_and_SubApp_internals_for_better_separation.md"

[[release_notes]]
file_name = "12688_Add_Tetrahedron_primitive_to_bevy_mathprimitives.md"

[[release_notes]]
file_name = "12734_Meshing_for_Annulus_primitive.md"

[[release_notes]]
file_name = "12829_Add_methods_iter_resources_and_iter_resources_mut.md"

[[release_notes]]
file_name = "12709_Error_info_has_been_added_to_LoadStateFailed.md"

[[release_notes]]
file_name = "12686_Meshing_for_Triangle3d_primitive.md"

[[release_notes]]
file_name = "12910_Implement_percentagecloser_filtering_PCF_for_point_lights.md"

[[release_notes]]
file_name = "12936_Optimize_Event_Updates.md"

[[release_notes]]
file_name = "13022_Make_AppExit_more_specific_about_exit_reason.md"

[[release_notes]]
file_name = "10973_Contextually_clearing_gizmos.md"

[[release_notes]]
file_name = "12904_Improve_par_iter_and_Parallel.md"

[[release_notes]]
file_name = "12755_Meshlet_continuous_LOD.md"

[[release_notes]]
file_name = "12672_Make_dynamic_linking_a_noop_on_wasm_targets.md"

[[release_notes]]
file_name = "9924_PerObject_Motion_Blur.md"

[[release_notes]]
file_name = "12622_Throttle_render_assets.md"

[[release_notes]]
file_name = "12889_Implement_GPU_frustum_culling.md"

[[release_notes]]
file_name = "10690_Upgrade_to_Taffy_04.md"

[[release_notes]]
file_name = "11426_Computed_State__Sub_States.md"

[[release_notes]]
file_name = "13162_Add_a_process_for_working_groups.md"

[[release_notes]]
file_name = "13199_Add_BufferVec_an_higherperformance_alternative_to_StorageB.md"

[[release_notes]]
file_name = "13233_Add_Annulusgizmos.md"

[[release_notes]]
file_name = "13270_Extrusion.md"

[[release_notes]]
file_name = "13200_Add_UV_channel_selection_to_StandardMaterial.md"

[[release_notes]]
file_name = "13009_Implement_fast_depth_of_field_as_a_postprocessing_effect.md"

[[release_notes]]
file_name = "11948_Add_Rounded_box_gizmos.md"

[[release_notes]]
file_name = "13057_Implement_volumetric_fog_and_volumetric_lighting_also_know.md"

[[release_notes]]
file_name = "13347_Add_on_unimplemented_Diagnostics_to_Most_Public_Traits.md"

[[release_notes]]
file_name = "11659_bevy_reflect_Custom_attributes.md"

[[release_notes]]
file_name = "13080_Deprecate_dynamic_plugins.md"

[[release_notes]]
file_name = "13417_implement_the_full_set_of_sort_methods_on_QueryIter.md"

[[release_notes]]
file_name = "13123_Implement_a_SystemBuilder_for_building_SystemParams.md"

[[release_notes]]
file_name = "13315_Add_Distribution_access_methods_for_ShapeSample_trait.md"

